const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const favKey='pricecheck:favorites';const historyKey='pricecheck:history';
const favorites=()=>new Set(JSON.parse(localStorage.getItem(favKey)||'[]'));const saveFavorites=s=>localStorage.setItem(favKey,JSON.stringify([...s]));const history=()=>JSON.parse(localStorage.getItem(historyKey)||'{}');const saveHistory=h=>localStorage.setItem(historyKey,JSON.stringify(h));

// Version affichée partout où le badge « nouvelle interface » est utilisé.
// Pour une prochaine mise à jour, il suffit de changer cette valeur.
const PRICECHECK_VERSION='V12.7';
function updateVersionBadge(){
  const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
  let node;
  while(node=walker.nextNode()){
    if(node.nodeValue.includes('🚀 V12.2 • nouvelle interface')){
      node.nodeValue=node.nodeValue.replaceAll('🚀 V12.2 • nouvelle interface',`🚀 ${PRICECHECK_VERSION} • nouvelle interface`);
    }
  }
}

// Les images locales du dépôt restent prioritaires : une image Supabase ancienne ne doit plus remplacer l'icône du catalogue.
const LOCAL_IMAGES={
  'Pickaxe of the God':'images/pog.svg','Paladium':'images/paladium-ore.svg','Titane':'images/titane.svg','Améthyste':'images/amethyste.svg','Rubis':'images/rubis.svg','Saphir':'images/saphir.svg','Émeraude':'images/emeraude.svg','Obsidienne':'images/obsidienne.svg',"Perle de l'End":'images/perle-end.svg','Machine industrielle':'images/crusher.svg','Four amélioré':'images/four.svg','Pioche Paladium':'images/pioche-paladium.svg','Casque Paladium':'images/casque-paladium.svg','Plastron Paladium':'images/plastron-paladium.svg','Pomme dorée':'images/pomme-doree.svg','Pain':'images/pain.svg','Pioche en améthyste':'images/pickaxe-amethyste.svg','Pelle en améthyste':'images/shovel-amethyste.svg','Hache en améthyste':'images/axe-amethyste.svg','Pioche en titane':'images/pickaxe-titane.svg','Pelle en titane':'images/shovel-titane.svg','Hache en titane':'images/axe-titane.svg','Marteau en paladium':'images/hammer-paladium.svg','Pioche en paladium vert':'images/pickaxe-paladium-vert.svg','Hache en paladium vert':'images/axe-paladium-vert.svg','Pioche en endium':'images/pickaxe-endium.svg','Hache en endium':'images/axe-endium.svg','Palaforge':'images/palaforge.svg','Palafurnace':'images/palafurnace.svg','Crusher':'images/crusher.svg','Cobblebreaker':'images/cobblebreaker.svg','Aimant':'images/aimant.svg','Dollars Stone':'images/dollars-stone.svg','Entonnoir en Paladium':'images/hopper-paladium.svg','Small Ring en Paladium':'images/small-ring.svg'
};
const localImageFor=name=>LOCAL_IMAGES[name]||null;

// Extension du catalogue : ressources, machines, objets et créatures de Paladium.
// Les prix ajoutés ici sont des estimations PriceCheck et non des prix officiels du serveur.
const CATALOG_EXPANSION_NAMES=[
'Paladium compressé','Lingot de Paladium Vert','Findium','Fragment d\'Endium','Pépite d\'Endium','Bloc de Paladium','Bloc de Titane','Bloc d\'Améthyste','Bloc de Rubis','Bloc de Saphir','Bloc d\'Émeraude','Obsidienne empoisonnée','Obsidienne de boom','Obsidienne gelée','Guardian Stone','Guardian Block','Palamachine','Palaforge','Palafurnace','Cobblebreaker','Crusher','Auto Crafter','Online Detector','Home Remover','Unclaim Finder Vert','Unclaim Finder Orange','Unclaim Finder Rouge','Unclaim Finder Bleu','Spike Iron','Spike Wood','Spike Gold','Spike Diamond','Spike Améthyste','Spike Titanium','Spike Paladium','Small Ring','Medium Ring','Big Ring','Aimant','Magnet','Hanglinder','Stick: Regen','Stick: Speed','Stick: Jump','Stick: Force','Chestplate Travel','Leggings Travel','Boots Travel','Anvil Améthyste','Anvil Titane','Anvil Paladium',
'Golem','Baby Wither','Wither de faction','Wither passif','Wither Funny','Wither Predator','Wither Thirsty','Wither Suprême','Green Zombie','Endium Mob Shinyy','Monstre mêlée Manelios','Monstre mage Manelios','Monstre distance Manelios','Monstre volant Manelios','Assassin Manelios','Tank Manelios','Mini-boss Davy-Jones','Boss Leviathan','Monstre mêlée Talikus','Monstre mage Talikus','Monstre distance Talikus','Monstre volant Talikus','Assassin Talikus','Tank Talikus','Mini-boss Tree','Boss Warmachine','Monstre mêlée Vitalys','Monstre mage Vitalys','Monstre distance Vitalys','Monstre volant Vitalys','Assassin Vitalys','Tank Vitalys','Mini-boss Chimera','Mini-boss Spinner'
];
const CATALOG_MACHINE_NAMES=new Set(['Palamachine','Palaforge','Palafurnace','Cobblebreaker','Crusher','Auto Crafter','Online Detector','Home Remover']);
const CATALOG_MOB_NAMES=new Set(CATALOG_EXPANSION_NAMES.slice(51));
const CATALOG_RARITIES=['Commun','Peu commun','Rare','Épique','Légendaire','Unique'];
function expansionCategory(name){if(CATALOG_MOB_NAMES.has(name))return'Mobs';if(name.startsWith('Bloc')||name.includes('Obsidienne'))return'Blocs';if(CATALOG_MACHINE_NAMES.has(name))return'Machines';if(name.includes('Finder')||name.includes('Ring')||name==='Aimant'||name==='Magnet'||name==='Hanglinder'||name.startsWith('Stick')||name.includes('Travel')||name.startsWith('Spike')||name.startsWith('Anvil'))return'Objets';return'Ressources'}
function expansionDescription(name){if(CATALOG_MOB_NAMES.has(name))return`Créature de Paladium — fiche communautaire à consulter pour ses caractéristiques et son rôle.`;if(CATALOG_MACHINE_NAMES.has(name))return`Machine ou équipement technique de Paladium. Données affichées comme estimation PriceCheck.`;return`Objet et ressource de Paladium. Données affichées comme estimation PriceCheck.`}
function addCatalogExpansion(){if(typeof ITEMS==='undefined')return;const existing=new Set(ITEMS.map(x=>norm(x[0])));const available=CATALOG_EXPANSION_NAMES.filter(n=>!existing.has(norm(n))).slice(0,Math.max(0,100-ITEMS.length));available.forEach((name,i)=>{const mob=CATALOG_MOB_NAMES.has(name),base=mob?0:Math.round((3500+i*1850)*([1,1.7,2.4,3.6,5.5,8][i%6]));const min=mob?0:Math.round(base*.85),max=mob?0:Math.round(base*1.18);ITEMS.push([name,[],expansionCategory(name),mob?'Rare':CATALOG_RARITIES[i%CATALOG_RARITIES.length],'images/default.svg',base,min,max,'∞',null,Math.min(20,1+(i%20)),expansionDescription(name),'']);});
  const cat=$('#cat');if(cat&&!cat.querySelector('option[value="Mobs"]')){const o=document.createElement('option');o.value='Mobs';o.textContent='Mobs';cat.appendChild(o)}
}

async function syncRemoteCatalog(){try{const cfgText=await fetch('auth-config.js?v=12.3',{cache:'no-store'}).then(r=>r.text());const url=(cfgText.match(/supabaseUrl:\s*["']([^"']+)/)||[])[1];const key=(cfgText.match(/supabaseAnonKey:\s*["']([^"']+)/)||[])[1];if(!url||!key)return;const r=await fetch(url+'/rest/v1/items?select=*',{headers:{apikey:key,Authorization:'Bearer '+key}});if(!r.ok)return;const remote=await r.json();for(const row of remote){const local=localImageFor(row.name);const next=[row.name,row.aliases||[],row.category,row.rarity,local||row.image||'images/default.svg',row.price,row.min_price,row.max_price,row.durability,row.damage,row.level,row.description,row.craft_text];const i=ITEMS.findIndex(x=>norm(x[0])===norm(row.name));if(i>=0)ITEMS[i]=next;else ITEMS.push(next)}}catch(e){console.warn('Catalogue distant indisponible',e)}}

const card=x=>{const fav=favorites().has(x[0]),conf=confidence(x),isMob=x[2]==='Mobs';return `<article class="item-card" data-name="${x[0].replaceAll('"','&quot;')}"><button class="fav ${fav?'on':''}" title="${fav?'Retirer des favoris':'Ajouter aux favoris'}" data-fav="${encodeURIComponent(x[0])}">${fav?'★':'☆'}</button><a class="item-link" href="item.html?item=${encodeURIComponent(x[0])}"><div class="item-top"><img src="${localImageFor(x[0])||x[4]||'images/default.svg'}" alt="${x[0]}" loading="lazy" onerror="this.onerror=null;this.src='images/default.svg'"><span class="cat">${x[2]}</span></div><h3>${x[0]}</h3><p class="desc">${x[11]}</p><span class="rarity ${RARITY_CLASS[x[3]]}">${x[3]}</span><div class="price">${isMob?'Non marchand':money(x[5])}</div>${isMob?'<div class="range">Créature • caractéristiques à consulter</div>':`<div class="range">${money(x[6])} → ${money(x[7])}</div>`}<div class="confidence ${conf[1]}">Confiance ${conf[0]}</div><div class="tags">${x[10]?`<span>⭐ ${x[10]}/20</span>`:''}${x[8]!==null?`<span>🔧 ${x[8]}</span>`:''}${x[9]?`<span>⚔️ ${x[9]}</span>`:''}</div></a></article>`};
function addXpLink(){const links=$('.links');if(links&&!links.querySelector('[href="xp.html"]'))links.insertAdjacentHTML('beforeend','<a href="xp.html">⚡ XP & POG</a>');if(links&&!links.querySelector('[href="changelog.html"]'))links.insertAdjacentHTML('beforeend','<a href="changelog.html">📝 Changelog</a>')}
function initCatalog(){const q=$('#q'),cat=$('#cat'),rar=$('#rar'),sort=$('#sort'),favOnly=$('#favOnly'),grid=$('#items'),count=$('#count'),favCount=$('#favCount');if(!q)return;function render(){let s=norm(q.value),c=cat.value,r=rar.value,so=sort.value,f=favOnly.checked,fs=favorites();let a=ITEMS.filter(x=>(!s||[x[0],...x[1],x[2],x[3]].map(norm).join(' ').includes(s))&&(c==='all'||x[2]===c)&&(r==='all'||x[3]===r)&&(!f||fs.has(x[0])));if(so==='priceUp')a.sort((x,y)=>x[5]-y[5]);if(so==='priceDown')a.sort((x,y)=>y[5]-x[5]);if(so==='rarUp')a.sort((x,y)=>RARITY_ORDER[x[3]]-RARITY_ORDER[y[3]]);if(so==='rarDown')a.sort((x,y)=>RARITY_ORDER[y[3]]-RARITY_ORDER[x[3]]);if(so==='name')a.sort((x,y)=>x[0].localeCompare(y[0],'fr'));grid.innerHTML=a.length?a.map(card).join(''):`<div class="empty">😕 Aucun item ne correspond à ces filtres.</div>`;count.textContent=a.length;favCount.textContent=fs.size;$$('[data-fav]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const set=favorites(),name=decodeURIComponent(b.dataset.fav);set.has(name)?set.delete(name):set.add(name);saveFavorites(set);render()})} [q,cat,rar,sort,favOnly].forEach(e=>e.addEventListener(e===q?'input':'change',render));const clear=$('#clear');if(clear)clear.onclick=()=>{q.value='';cat.value='all';rar.value='all';sort.value='none';favOnly.checked=false;render()};render()}
function initMarket(){const sel=$('#marketItem'),qty=$('#qty'),dur=$('#durability'),out=$('#marketOut'),record=$('#recordPrice'),observed=$('#observedPrice'),historyBox=$('#historyBox');if(!sel)return;ITEMS.filter(x=>x[2]!=='Mobs').forEach(x=>{const o=document.createElement('option');o.value=x[0];o.textContent=x[0];sel.appendChild(o)});function calc(){const x=getItem(sel.value);if(!x)return;const q=Math.max(1,+qty.value||1),d=Math.max(0,Math.min(100,+dur.value||100)),factor=x[8]&&x[8]!=='∞'?d/100:1,value=Math.round(x[5]*factor*q);out.innerHTML=`<b>${money(value)}</b><span>Valeur estimée pour ${q} unité${q>1?'s':''}${x[8]&&x[8]!=='∞'?` à ${d}% de durabilité`:''}.</span><small>Base: ${money(x[5])} • fourchette ${money(x[6])}–${money(x[7])}</small>`}function drawHistory(){const h=history()[sel.value]||[];historyBox.innerHTML=h.length?`<div class="history-bars">${h.slice(-10).map(v=>`<div style="height:${Math.max(8,Math.min(100,v.value/Math.max(...h.map(a=>a.value))*100))}%" title="${money(v.value)} • ${v.date}"></div>`).join('')}</div><p class="muted small">Tes observations locales — elles ne sont pas présentées comme des prix officiels.</p>`:'<p class="muted">Aucun historique local. Ajoute tes propres observations de marché.</p>'}[sel,qty,dur].forEach(e=>e.addEventListener('input',()=>{calc();drawHistory()}));if(record)record.onclick=()=>{const x=getItem(sel.value),v=+observed.value;if(!x||!v||v<0)return;const h=history();h[x[0]]=[...(h[x[0]]||[]),{value:Math.round(v),date:new Date().toLocaleDateString('fr-FR')}].slice(-20);saveHistory(h);observed.value='';drawHistory()};sel.value=ITEMS[0][0];calc();drawHistory()}
function initXp(){if(typeof JOB_XP==='undefined')return;const job=$('#jobSelect'),action=$('#xpAction'),minLevel=$('#xpLevel'),xpRows=$('#xpRows'),best=$('#xpBest'),need=$('#jobNeed'),pogLevel=$('#pogLevel'),pogInfo=$('#pogInfo'),pogNext=$('#pogNext');if(!job)return;Object.keys(JOB_XP).forEach(j=>{const o=document.createElement('option');o.value=j;o.textContent=j;job.appendChild(o)});function renderJob(){const j=job.value,rows=jobXpRows(j),a=action.value,level=Math.max(1,Math.min(20,+minLevel.value||1)),filtered=rows.filter(r=>a==='all'||r[1]===a);xpRows.innerHTML=filtered.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td><b>${String(r[2]).replace('.',',')} XP</b></td><td>Niv. ${r[3]}+</td></tr>`).join('')||'<tr><td colspan="4">Aucune donnée pour ce filtre.</td></tr>';const top=jobBestRows(j).slice(0,3);best.innerHTML=top.map((r,i)=>`<div class="rank"><b>#${i+1}</b><span>${r[0]}<small>${r[1]} • débloqué niv. ${r[3]}</small></span><strong>${String(r[2]).replace('.',',')} XP</strong></div>`).join('');const target=JOB_LEVEL_XP[Math.min(level-1,JOB_LEVEL_XP.length-1)];need.innerHTML=`<b>Niveau ${level}${level<20?` → ${level+1}`:''}</b><span>${level<20?`XP de passage : ${target.toLocaleString('fr-FR')} XP`:'Niveau 20 atteint'}</span><small>Prérequis indicatif : ${Math.round(target/5).toLocaleString('fr-FR')} XP</small>`}function renderPog(){const l=Math.max(1,Math.min(100,+pogLevel.value||1)),tier=pogTier(l),next=POG_BLOCKS_TO_NEXT[l];pogInfo.innerHTML=`<b>Niveau ${l}</b><span>${tier.label}</span><small>${tier.blocks.length?tier.blocks.join(' • '):'Aucun bloc OS documenté à ce palier.'}</small>`;pogNext.innerHTML=l<100?`<b>${next.toLocaleString('fr-FR')} blocs</b><span>environ pour passer de ${l} → ${l+1}</span><small>Les blocs conseillés sont ceux que la POG OS à ce niveau.</small>`:'<b>Niveau 100 🎉</b><span>Auto Smelt peut ensuite être ajouté à la POG.</span>'}[job,action,minLevel].forEach(e=>e.addEventListener('input',renderJob));pogLevel.addEventListener('input',renderPog);renderJob();renderPog()}
async function boot(){addCatalogExpansion();await syncRemoteCatalog();updateVersionBadge();addXpLink();initCatalog();initMarket();initXp();const y=$('#year');if(y)y.textContent=new Date().getFullYear()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();