(() => {
  'use strict';
  if (!location.pathname.endsWith('/changelog.html')) return;
  const ready=()=>{
    const main=document.querySelector('main')||document.body;if(main.querySelector('.pc-live-changelog'))return;
    const entry=document.createElement('section');entry.className='pc-live-changelog';
    entry.innerHTML='<div class="pc-live-date">26/08/2026 • mise à jour PriceCheck</div><h2>V17 — Économie, administration & communauté</h2><ul><li>🛡️ Les administrateurs affichent maintenant leur état <b>🟢 Connecté</b> ou <b>⚪ Pas connecté</b> dans le panneau admin.</li><li>💰 Budget et portefeuille du Profil sont synchronisés avec la même donnée serveur.</li><li>🪙 Ajout du classement communautaire <b>PB</b> avec un Top 3.</li><li>⛏️ Ajout du <b>Lingot d’Andium</b> et du <b>Nugget d’Andium</b> au catalogue.</li><li>🎮 Renforcement du style visuel Minecraft / Paladium dans les nouveaux éléments de l’interface.</li></ul><small>Les nouveautés sont publiées uniquement lorsqu’elles sont réellement présentes dans le projet.</small>';
    const style=document.createElement('style');style.textContent='.pc-live-changelog{position:relative;overflow:hidden;margin:0 0 20px;padding:20px;border:1px solid #38bdf855;border-radius:18px;background:linear-gradient(135deg,#0f172a,#111827 55%,#172554);box-shadow:0 16px 40px #0004}.pc-live-changelog:after{content:"⛏️";position:absolute;right:18px;top:8px;font-size:72px;opacity:.12;pointer-events:none}.pc-live-changelog h2{margin:5px 0 10px}.pc-live-changelog ul{margin:0;padding-left:20px;color:#cbd5e1;line-height:1.7}.pc-live-changelog small,.pc-live-date{color:#94a3b8}.pc-live-date{font-size:12px;font-weight:900}';document.head.appendChild(style);main.prepend(entry);
  };if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready,{once:true});else ready();
})();