(() => {
  'use strict';
  if (!location.pathname.endsWith('/changelog.html')) return;
  const ready=()=>{
    const main=document.querySelector('main')||document.body;if(main.querySelector('.pc-live-changelog'))return;
    const entry=document.createElement('section');entry.className='pc-live-changelog';
    entry.innerHTML='<div class="pc-live-date">23/08/2026 • 18:39 (UTC+2)</div><h2>V14.0 — Profil, classement, budget & catalogue renforcés</h2><ul><li>🏆 Correction des onglets du classement communautaire : Wallet, Mineur, Fermier, Chasseur, Alchimiste et POG peuvent maintenant être sélectionnés sans être bloqués.</li><li>🟢 Le compteur de joueurs actifs dispose d’un fallback local pour rester visible même si Supabase répond mal.</li><li>💾 Les niveaux de métiers et le niveau POG restent persistants et sont restaurés automatiquement.</li><li>💰 Le portefeuille, les P$ et les PB utilisent les mêmes données sur le profil et le Budget.</li><li>🧹 Le portefeuille permanent est retiré du Catalogue pour éviter le doublon ; il reste accessible depuis Budget et Profil.</li><li>🌳 Ajout de nouvelles variétés de bois moddés : Jacaranda, Acajou, Ébène, Palmier, Baobab, Sakura, Bambou et Acacia.</li><li>🖼️ Ajout d’icônes locales dédiées aux nouveaux bois et vérification des images des bouteilles d’XP 1000 XP.</li><li>✨ L’animation de la barre de profil tourne désormais en boucle continue, avec un cycle inférieur à une seconde et sans longue pause.</li><li>⚡ Suppression de l’observateur DOM qui pouvait provoquer des rafraîchissements en boucle sur la barre de profil.</li></ul><small>Mise à jour enregistrée avec date et heure de publication.</small>';
    const style=document.createElement('style');style.textContent='.pc-live-changelog{margin:0 0 20px;padding:18px;border:1px solid #334155;border-radius:17px;background:linear-gradient(135deg,#101827,#17112a)}.pc-live-changelog h2{margin:5px 0 10px}.pc-live-changelog ul{margin:0;padding-left:20px;color:#cbd5e1;line-height:1.7}.pc-live-changelog small,.pc-live-date{color:#94a3b8}.pc-live-date{font-size:12px;font-weight:800}';document.head.appendChild(style);main.prepend(entry);
  };if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready,{once:true});else ready();
})();
