(()=>{
'use strict';
const cfg=window.PRICECHECK_AUTH||{};
if(!window.supabase||!cfg.supabaseUrl||!cfg.supabaseAnonKey||!location.pathname.endsWith('/admin.html'))return;
const client=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
const q=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function getMe(){const {data:{session}}=await client.auth.getSession();if(!session?.user)return null;const {data}=await client.from('admins').select('user_id,role').eq('user_id',session.user.id).maybeSingle();return data?{...data,user:session.user}:null}
function addPanel(me){if(!me||me.role!=='creator'||q('#creatorPanel'))return;const style=document.createElement('style');style.textContent=`#creatorPanel{margin:15px 0;padding:18px;border:1px solid #fbbf2455;border-radius:17px;background:linear-gradient(145deg,#211a0d,#111827);box-shadow:0 12px 38px #0005}.creator-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.creator-list{display:grid;gap:8px;margin-top:12px}.creator-row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:11px;border:1px solid #334155;border-radius:11px;background:#0b111d}.creator-actions{display:flex;gap:6px;flex-wrap:wrap}.creator-input{width:100%;padding:10px;border:1px solid #334155;border-radius:10px;background:#070910;color:#fff}.creator-small{font-size:12px;color:#94a3b8}@media(max-width:700px){.creator-grid{grid-template-columns:1fr}.creator-row{align-items:flex-start;flex-direction:column}}`;document.head.appendChild(style);
const panel=document.createElement('section');panel.id='creatorPanel';panel.innerHTML=`<h2>👑 Centre Créateur</h2><p class="muted">Tu as le niveau supérieur aux admins : gestion des admins et contrôle complet du catalogue.</p><div class="creator-grid"><div><label class="creator-small">UUID Supabase du joueur à ajouter</label><input id="creatorUserId" class="creator-input" placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"><button class="btn primary" id="creatorAdd" style="margin-top:8px">➕ Ajouter admin</button></div><div><label class="creator-small">Retirer un admin</label><p class="creator-small">Le créateur actuel reste protégé contre une suppression accidentelle.</p></div></div><div id="creatorList" class="creator-list"><p class="muted">Chargement…</p></div>`;
const target=q('#panel');if(target)target.insertBefore(panel,target.firstElementChild);
async function load(){const list=q('#creatorList');if(!list)return;const {data,error}=await client.from('admins').select('user_id,role,created_at').order('created_at');if(error){list.innerHTML=`<p class="muted">❌ ${esc(error.message)}</p>`;return}list.innerHTML=(data||[]).map(a=>`<div class="creator-row"><div><b>${a.role==='creator'?'👑 Créateur':'🛡️ Admin'}</b><div class="creator-small">${esc(a.user_id)}</div></div><div class="creator-actions">${a.role==='admin'?`<button class="btn" data-promote="${esc(a.user_id)}">👑 Promouvoir</button><button class="btn danger" data-remove="${esc(a.user_id)}">🗑️ Retirer</button>`:'<span class="creator-small">Compte créateur</span>'}</div></div>`).join('')||'<p class="muted">Aucun administrateur.</p>';
list.querySelectorAll('[data-promote]').forEach(b=>b.onclick=async()=>{const id=b.dataset.promote;if(!confirm('Promouvoir cet admin au rôle créateur ? Cela remplacera le créateur actuel.'))return;const {error}=await client.from('admins').update({role:'admin'}).eq('role','creator');if(error){alert(error.message);return}const r=await client.from('admins').update({role:'creator'}).eq('user_id',id);if(r.error)alert(r.error.message);await load()});
list.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{if(!confirm('Retirer cet administrateur ?'))return;const {error}=await client.from('admins').delete().eq('user_id',b.dataset.remove).eq('role','admin');if(error)alert(error.message);await load()});}
q('#creatorAdd').onclick=async()=>{const id=q('#creatorUserId').value.trim();if(!id)return alert('Entre un UUID Supabase.');const {error}=await client.from('admins').upsert({user_id:id,role:'admin'},{onConflict:'user_id'});if(error){alert('Impossible d’ajouter cet admin : '+error.message);return}q('#creatorUserId').value='';await load()};
load();
}
async function boot(){const wait=async()=>{const me=await getMe();if(me){const panel=q('#panel');if(panel)addPanel(me);else setTimeout(wait,150)}};wait()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
