const ITEMS = [
['Pickaxe of the God',['Pog','POG'],'Outils','Unique','images/pog.svg',150000,100000,220000,'∞','Évolutif',100,'Pioche évolutive haut de gamme.','Craft évolutif'],
['Paladium',['Pala'],'Minerais','Légendaire','images/paladium-ore.svg',1200,800,1700,null,null,8,'Minerai avancé de progression.','Minerai obtenu en jeu'],
['Titane',['Titanium'],'Minerais','Épique','images/titane.svg',650,450,900,null,null,6,'Minerai de progression.','Minerai obtenu en jeu'],
['Améthyste',['Ame','Amé'],'Minerais','Rare','images/amethyste.svg',300,200,450,null,null,1,'Minerai spécial de progression.','Minerai obtenu en jeu'],
['Rubis',['Ruby'],'Minerais','Rare','images/rubis.svg',500,350,700,null,null,null,'Ressource précieuse du Palamod.','Selon la recette'],
['Saphir',['Saph'],'Minerais','Rare','images/saphir.svg',450,300,650,null,null,null,'Ressource précieuse du Palamod.','Selon la recette'],
['Émeraude',['Emerald','Emer'],'Minerais','Peu commun','images/emeraude.svg',280,180,400,null,null,null,'Ressource minérale verte.','Selon la recette'],
['Obsidienne',['Obsi'],'Ressources','Peu commun','images/obsidienne.svg',100,60,160,null,null,null,'Ressource polyvalente.','Selon la recette'],
["Perle de l'End",['Perle','Ender Pearl'],'Ressources','Rare','images/perle-end.svg',550,400,800,null,null,null,'Ressource de l’End.','Obtenue en jeu'],
['Machine industrielle',['Machine'],'Machines','Épique','images/crusher.svg',18000,12000,28000,null,null,null,'Machine de production.','Craft machine à confirmer'],
['Four amélioré',['Four'],'Machines','Rare','images/four.svg',6500,4500,9000,null,null,null,'Four amélioré.','Craft machine à confirmer'],
['Pioche Paladium',['Pioche Pala'],'Outils','Légendaire','images/pioche-paladium.svg',18000,13000,25000,4999,'+8',8,'Pioche Paladium : 4 999 de durabilité et +8 dégâts.','Craft via progression/Grinder'],
['Casque Paladium',['Casque Pala'],'Armures','Légendaire','images/casque-paladium.svg',16000,11000,23000,4999,null,null,'Pièce d’armure Paladium.','Craft armure'],
['Plastron Paladium',['Plastron Pala'],'Armures','Légendaire','images/plastron-paladium.svg',30000,22000,42000,4999,null,null,'Pièce d’armure Paladium.','Craft armure'],
['Pomme dorée',['Pomme','Golden Apple'],'Nourriture','Rare','images/pomme-doree.svg',2500,1800,3500,null,null,null,'Nourriture spéciale.','Craft vanilla'],
['Pain',['Bread'],'Nourriture','Commun','images/pain.svg',80,50,120,null,null,11,'Nourriture de base.','3 blés'],
['Pioche en améthyste',['Pioche Améthyste'],'Outils','Rare','images/pickaxe-amethyste.svg',900,600,1300,1999,'+5',null,'Outil en améthyste.','Table de craft'],
['Pelle en améthyste',['Pelle Améthyste'],'Outils','Rare','images/shovel-amethyste.svg',750,500,1100,1999,'+4',null,'Pelle en améthyste.','Table de craft'],
['Hache en améthyste',['Hache Améthyste'],'Outils','Rare','images/axe-amethyste.svg',1000,700,1400,1999,'+6',null,'Hache en améthyste.','Table de craft'],
['Pioche en titane',['Pioche Titane'],'Outils','Épique','images/pickaxe-titane.svg',2200,1500,3200,2999,'+5.5',6,'Pioche en titane.','Table de craft'],
['Pelle en titane',['Pelle Titane'],'Outils','Épique','images/shovel-titane.svg',1900,1300,2800,2999,'+4.5',6,'Pelle en titane.','Table de craft'],
['Hache en titane',['Hache Titane'],'Outils','Épique','images/axe-titane.svg',2500,1700,3600,2999,'+6.5',6,'Hache en titane.','Table de craft'],
['Marteau en paladium',['Hammer Paladium'],'Outils','Légendaire','images/hammer-paladium.svg',12000,8000,17000,4999,null,null,'Marteau qui creuse une zone 3×3.','Grinder'],
['Pioche en paladium vert',['Pioche Pala Vert'],'Outils','Légendaire','images/pickaxe-paladium-vert.svg',19000,13000,27000,4999,'+8',null,'Pioche Paladium vert.','Craft avancé'],
['Hache en paladium vert',['Hache Pala Vert'],'Outils','Légendaire','images/axe-paladium-vert.svg',21000,15000,30000,4999,'+9',null,'Hache Paladium vert.','Craft avancé'],
['Pioche en endium',['Pioche Endium'],'Outils','Unique','images/pickaxe-endium.svg',50000,35000,70000,4999,'+9.3',20,'Pioche Endium, niveau 20 Mineur.','Craft avancé'],
['Hache en endium',['Hache Endium'],'Outils','Unique','images/axe-endium.svg',52000,36000,75000,4999,'+10.3',20,'Hache Endium très haut niveau.','Craft avancé'],
['Palaforge',['Forge Paladium'],'Machines','Légendaire','images/palaforge.svg',35000,24000,50000,null,null,14,'Machine de recyclage des outils et armures moddés.','1 findium + 4 palafurnaces + 4 blocs de briques'],
['Palafurnace',['Four Paladium'],'Machines','Épique','images/palafurnace.svg',14000,9500,20000,null,null,null,'Four moddé pouvant être amélioré.','Craft machine'],
['Crusher',['Broyeur'],'Machines','Épique','images/crusher.svg',12000,8000,18000,null,null,8,'Machine de traitement des fruits de minerais.','Craft machine'],
['Cobblebreaker',['Cobble Breaker'],'Machines','Épique','images/cobblebreaker.svg',10000,7000,15000,null,null,null,'Machine de recyclage de cobble.','Craft machine'],
['Aimant',['Magnet'],'Ressources','Rare','images/aimant.svg',3500,2300,5000,null,null,7,'Attire les objets au sol dans un rayon de 6 blocs.','2 lingots paladium + 5 blocs fer'],
['Dollars Stone',['Dollar Stone'],'Ressources','Épique','images/dollars-stone.svg',7000,4500,10000,null,null,8,'Vend automatiquement certains blocs au shop.','1 voidstone + 4 perles End + composants paladium/améthyste'],
['Entonnoir en Paladium',['Paladium Hopper'],'Machines','Légendaire','images/hopper-paladium.svg',9000,6000,13000,null,null,9,'Transfère les objets par stack.','1 coffre titane + 5 lingots paladium'],
['Small Ring en Paladium',['Small Ring'],'Ressources','Épique','images/small-ring.svg',3000,2000,4500,400,null,null,'Ring pouvant rendre jusqu’à 400 de durabilité.','Palamachine'],
['Findium',['Find'],'Minerais','Légendaire','images/paladium-ore.svg',4200,2800,6000,null,null,12,'Minerai rare utilisé dans plusieurs crafts avancés.','Obtenu en jeu · prix indicatif'],
['Voidstone',['Void Stone'],'Ressources','Légendaire','images/obsidienne.svg',2600,1700,3800,null,null,12,'Ressource sombre utilisée pour des équipements et machines avancés.','Obtenue en jeu · prix indicatif'],
['Bloc de Paladium',['Bloc Pala','Paladium Block'],'Blocs','Légendaire','images/paladium-ore.svg',10800,7500,14500,null,null,8,'Bloc compact de minerai de Paladium.','9 Paladium · valeur indicative'],
['Lingot de Paladium',['Lingot Pala','Paladium Ingot'],'Lingots','Légendaire','images/paladium-ore.svg',1300,900,1900,null,null,8,'Lingot utilisé dans de nombreux crafts avancés.','Fusion / traitement · valeur indicative'],
['Lingot de Titane',['Lingot Titan','Titanium Ingot'],'Lingots','Épique','images/titane.svg',720,500,1050,null,null,6,'Lingot de titane pour les outils et équipements.','Fusion / traitement · valeur indicative'],
['Bloc de Titane',['Bloc Titan','Titanium Block'],'Blocs','Épique','images/titane.svg',6000,4200,9000,null,null,6,'Bloc compact de titane.','9 lingots de Titane · valeur indicative'],
['Bloc d’Améthyste',['Bloc Ame','Amethyst Block'],'Blocs','Rare','images/amethyste.svg',2700,1900,3900,null,null,1,'Bloc d’améthyste décoratif et de stockage.','9 Améthystes · valeur indicative'],
['Bloc de Rubis',['Bloc Ruby','Ruby Block'],'Blocs','Rare','images/rubis.svg',4500,3200,6300,null,null,null,'Bloc de rubis compact.','9 Rubis · valeur indicative'],
['Bloc de Saphir',['Bloc Saph','Sapphire Block'],'Blocs','Rare','images/saphir.svg',4050,2850,5700,null,null,null,'Bloc de saphir compact.','9 Saphirs · valeur indicative'],
['Bloc d’Émeraude',['Bloc Emer','Emerald Block'],'Blocs','Peu commun','images/emeraude.svg',2500,1700,3600,null,null,null,'Bloc d’émeraude compact.','9 Émeraudes · valeur indicative'],
['Épée Paladium',['Sword Pala','Épée Pala'],'Armes','Légendaire','images/epee-paladium.svg',22000,15000,32000,4999,'+12',10,'Épée en Paladium destinée au combat avancé.','Craft avancé · prix indicatif'],
['Pioche en Rubis',['Pioche Ruby'],'Outils','Rare','images/pickaxe-amethyste.svg',1400,950,2100,1999,'+5.5',null,'Pioche en rubis, estimation communautaire.','Craft avancé · prix indicatif'],
['Pioche en Saphir',['Pioche Sapphire'],'Outils','Rare','images/pickaxe-amethyste.svg',1300,900,2000,1999,'+5.5',null,'Pioche en saphir, estimation communautaire.','Craft avancé · prix indicatif'],
['Pioche en Émeraude',['Pioche Emerald'],'Outils','Peu commun','images/pickaxe-amethyste.svg',900,600,1400,1999,'+5',null,'Pioche en émeraude, estimation communautaire.','Craft avancé · prix indicatif'],
['Bloc de Fer',['Iron Block'],'Blocs','Commun','images/obsidienne.svg',180,120,260,null,null,null,'Bloc métallique de base utilisé comme composant.','Craft vanilla · icône provisoire'],
['Coffre en Titane',['Titanium Chest'],'Machines','Épique','images/machine.svg',8500,6000,12000,null,null,null,'Coffre renforcé destiné au stockage avancé.','Craft avancé · prix indicatif']
];
const RARITY_ORDER={Commun:0,'Peu commun':1,Rare:2,'Épique':3,'Légendaire':4,Unique:5};
const RARITY_CLASS={Commun:'common','Peu commun':'uncommon',Rare:'rare',Épique:'epic',Légendaire:'legendary',Unique:'unique'};
const CATEGORIES=['Minerais','Lingots','Blocs','Ressources','Machines','Outils','Armes','Armures','Nourriture','Cosmétiques'];
function norm(v){return String(v??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’']/g,' ').replace(/[-_]/g,' ').replace(/\s+/g,' ').trim()}
function money(v){return Number(v||0).toLocaleString('fr-FR')+' $'}
function confidence(item){const width=(item[7]-item[6])/Math.max(item[5],1);return width<=.7?['Bonne','good']:width<=1.05?['Moyenne','medium']:['Faible','low']}
function getItem(name){const n=norm(name);return ITEMS.find(x=>norm(x[0])===n||x[1].some(a=>norm(a)===n))}
(function(){const link=document.createElement('link');link.rel='stylesheet';link.href='ui-polish.css?v=12.7';document.head.appendChild(link);})();
