// Catalogue étendu V12.7 — 50 entrées supplémentaires pour atteindre 100 items.
// Les prix sont des estimations communautaires et ne sont pas des prix officiels.
const EXTRA_ITEMS=[
['Houe en améthyste',['Houe Améthyste'],'Outils','Rare','images/pickaxe-amethyste.svg',700,450,1050,1999,null,4,'Houe du Palamod pour la culture.','Table de craft · données wiki'],
['Houe en titane',['Houe Titane'],'Outils','Épique','images/pickaxe-titane.svg',1800,1200,2600,2999,null,12,'Houe en titane.','Table de craft · données wiki'],
['Houe en paladium',['Houe Paladium'],'Outils','Légendaire','images/pioche-paladium.svg',9000,6500,13000,4999,null,17,'Houe en paladium.','Craft avancé · estimation'],
['Houe en endium',['Houe Endium'],'Outils','Unique','images/pickaxe-endium.svg',32000,22000,48000,4999,null,20,'Houe en endium.','Craft avancé · estimation'],
['Outil de construction en améthyste',['Builder Améthyste'],'Outils','Rare','images/amethyste.svg',2200,1500,3200,null,null,4,'Pose jusqu’à 36 blocs simultanément.','Niveau Mineur 4 · wiki'],
['Outil de construction en titane',['Builder Titane'],'Outils','Épique','images/titane.svg',5000,3500,7500,null,null,12,'Pose jusqu’à 64 blocs simultanément.','Niveau Mineur 12 · wiki'],
['Outil de construction en paladium',['Builder Paladium'],'Outils','Légendaire','images/paladium-ore.svg',14000,9500,21000,null,null,17,'Pose jusqu’à 100 blocs simultanément.','Niveau Mineur 17 · wiki'],
['Outil de construction en endium',['Builder Endium'],'Outils','Unique','images/pickaxe-endium.svg',40000,28000,60000,null,null,20,'Pose jusqu’à 400 blocs simultanément.','Niveau Mineur 20 · wiki'],
['Palamachine',['Pala Machine'],'Machines','Légendaire','images/palaforge.svg',10000,7000,15000,null,null,null,'Machine essentielle pour les rings et objets de Palamod.','8 roches + 1 Paladium compressé · wiki'],
['Grinder',['Recycleur'],'Machines','Légendaire','images/crusher.svg',16000,11000,24000,null,null,null,'Machine utilisée pour recycler et améliorer certains équipements.','Craft machine · wiki'],
['Table d’Alchimiste',['Alchemy Creator'],'Machines','Épique','images/four.svg',7000,4500,11000,null,null,null,'Permet de fabriquer des flèches et potions modifiées.','Craft machine · wiki'],
['Autocrafter',['Auto Crafter'],'Machines','Légendaire','images/machine.png',12000,8000,18000,null,null,null,'Machine automatisant certains crafts avec ses composants.','Craft machine · estimation'],
['Injecteur',['Injector'],'Machines','Rare','images/machine.png',1800,1200,2800,null,null,null,'Composant de l’Autocrafter.','Craft machine · wiki'],
['Récepteur',['Receiver'],'Machines','Rare','images/machine.png',1800,1200,2800,null,null,null,'Composant de l’Autocrafter.','Craft machine · wiki'],
['Distributeur',['Giver'],'Machines','Rare','images/machine.png',1800,1200,2800,null,null,null,'Composant de l’Autocrafter.','Craft machine · wiki'],
['Tuyau en Paladium',['Paladium Pipe'],'Machines','Épique','images/paladium-ore.svg',1600,1000,2500,null,null,null,'Tuyau de l’Autocrafter, vitesse indicative : 1 seconde.','Composant Autocrafter · wiki'],
['Tuyau en Paladium vert',['Green Paladium Pipe'],'Machines','Légendaire','images/paladium-ore.svg',2800,1800,4200,null,null,null,'Tuyau de l’Autocrafter, vitesse indicative : 0,75 seconde.','Composant Autocrafter · wiki'],
['Tuyau en Endium mixé',['Mixed Endium Pipe'],'Machines','Unique','images/pickaxe-endium.svg',6500,4500,9500,null,null,null,'Tuyau de l’Autocrafter, vitesse indicative : 0,50 seconde.','Composant Autocrafter · wiki'],
['Quartz électrifié',['Empowered Quartz'],'Ressources','Épique','images/default.svg',3200,2200,4800,null,null,null,'Composant utilisé dans certaines structures de pillage.','Craft / obtention · wiki'],
['Quartz compressé',['Compressed Quartz'],'Ressources','Rare','images/default.svg',900,600,1400,null,null,null,'Composant servant au quartz électrifié.','Craft · wiki'],
['Chercheur de home',['Home Finder'],'Ressources','Légendaire','images/default.svg',8500,5500,12500,null,null,null,'Bloc principal de la structure du Home Finder.','Craft · wiki'],
['Pierre d’habitation',['Housing Stone'],'Ressources','Épique','images/obsidienne.svg',4500,3000,7000,8,null,null,'Pierre liée aux mécaniques de combat des gardiens.','Craft · wiki'],
['Pierre infusée',['Infused Stone'],'Ressources','Rare','images/obsidienne.svg',1800,1200,2800,null,null,null,'Composant évolutif pour la pierre d’habitation.','Craft · wiki'],
['Brouilleur de coordonnées',['Coordinate Jammer'],'Machines','Légendaire','images/default.svg',9500,6500,14000,null,null,null,'Modifie les coordonnées d’une zone donnée.','Craft · wiki'],
['Guardian Block',['Bloc gardien'],'Mobs','Légendaire','images/golem.svg',4200,2800,6500,null,null,null,'Composant principal de création du Golem.','4 roches + Paladium compressé + titane · wiki'],
['Guardian Keeper',['Golem Keeper'],'Mobs','Épique','images/golem.svg',5500,3500,8500,null,null,null,'Stocke les pierres contenant l’âme de vos Golems.','Autour du Golem · wiki'],
['Guardian Box Block',['Bloc boîte à Golem'],'Mobs','Épique','images/golem.svg',3800,2500,6000,null,null,null,'Composant principal de la boîte à Golems.','Autour du Golem · wiki'],
['Guardian Box Frame',['Cadre boîte à Golem'],'Mobs','Rare','images/golem.svg',900,600,1400,null,null,null,'Composant de la boîte à Golems.','Autour du Golem · wiki'],
['Guardian Stone',['Pierre gardienne'],'Mobs','Légendaire','images/golem.svg',7000,4500,11000,null,null,null,'Conserve l’âme d’un Golem.','Obtention via Golem · wiki'],
['Guardian Renamer',['Renommeur de Golem'],'Mobs','Rare','images/golem.svg',1200,800,1800,null,null,null,'Permet de renommer un Golem.','Autour du Golem · wiki'],
['Guardian Whitelist',['Whitelist Golem'],'Mobs','Rare','images/golem.svg',1500,1000,2200,null,null,null,'Permet de définir les joueurs ignorés par un Golem.','Autour du Golem · wiki'],
['Wrench',['Clé de réparation'],'Outils','Rare','images/default.svg',900,600,1400,null,null,null,'Outil utilisé pour réparer un Golem dans certaines situations.','Autour du Golem · wiki'],
['Machine à croquettes',['Guardian Food Machine'],'Machines','Légendaire','images/four.svg',9000,6000,14000,null,null,null,'Machine permettant de fabriquer les croquettes des Golems.','2 pommadiums + findium + eau + Paladium compressé + obsidienne + étoile du Nether · wiki'],
['Croquette',['Food'],'Nourriture','Rare','images/pomme-doree.svg',250,150,400,null,null,null,'Nourriture spéciale pour Golem.','Machine à croquettes · wiki'],
['Unclaim Finder vert',['Green Finder'],'Ressources','Rare','images/emeraude.svg',4500,3000,7000,140,null,null,'Scanne un chunk et indique la présence de stockage.','Palamachine · wiki'],
['Unclaim Finder orange',['Orange Finder'],'Ressources','Épique','images/pomme-doree.svg',7000,4500,11000,140,null,null,'Version améliorée de l’Unclaim Finder.','Palamachine · estimation'],
['Unclaim Finder rouge',['Red Finder'],'Ressources','Légendaire','images/rubis.svg',11000,7500,17000,140,null,null,'Version avancée de l’Unclaim Finder.','Palamachine · estimation'],
['Unclaim Finder bleu',['Blue Finder'],'Ressources','Unique','images/saphir.svg',18000,12000,27000,140,null,null,'Version haut de gamme de l’Unclaim Finder.','Palamachine · estimation'],
['Coffre en Paladium',['Paladium Chest'],'Blocs','Légendaire','images/paladium-ore.svg',9000,6000,14000,null,null,null,'Coffre moddé avec emplacements de réparation et de stockage.','Stockages · wiki'],
['Coffre en Endium',['Endium Chest'],'Blocs','Unique','images/pickaxe-endium.svg',26000,18000,38000,null,null,null,'Coffre moddé haut de gamme avec réparation Endium.','Stockages · wiki'],
['Golem',['Guardian Golem'],'Mobs','Unique','images/golem.svg',45000,30000,70000,null,null,40,'Mob évolutif pouvant farmer des minerais et assurer diverses fonctions. Niveau maximal : 40.','173 lingots Paladium + 8 lingots Titane + 8 roches · wiki'],
['Mini golem',['Mini Golem'],'Mobs','Légendaire','images/golem.svg',18000,12000,28000,140,null,7,'Version transportable du Golem, disponible à partir du niveau 7 Chasseur.','Guardian Stone + 3 blocs de Paladium · wiki'],
['Serpent',['Snake'],'Mobs','Rare','images/mob.svg',300,120,550,null,null,null,'Créature modifiée présente dans les Farmlands.','Créature de Farmlands · estimation'],
['Méduse',['Jellyfish'],'Mobs','Rare','images/mob.svg',350,150,650,null,null,null,'Créature modifiée présente dans les Farmlands.','Créature de Farmlands · estimation'],
['Chèvre',['Goat'],'Mobs','Rare','images/mob.svg',250,100,500,null,null,null,'Créature modifiée présente dans les Farmlands.','Créature de Farmlands · estimation'],
['Panda',['Panda'],'Mobs','Rare','images/mob.svg',400,180,700,null,null,null,'Créature modifiée présente dans les Farmlands.','Créature de Farmlands · estimation'],
['Tortue',['Turtle'],'Mobs','Rare','images/mob.svg',280,110,520,null,null,null,'Créature modifiée présente dans les Farmlands.','Créature de Farmlands · estimation'],
['Dauphin',['Dolphin'],'Mobs','Rare','images/mob.svg',320,140,600,null,null,null,'Créature modifiée présente dans les Farmlands.','Créature de Farmlands · estimation'],
['Éléphant',['Elephant'],'Mobs','Épique','images/mob.svg',900,450,1500,null,null,null,'Créature modifiée présente dans les Farmlands.','Créature de Farmlands · estimation'],
['Crabe',['Crab'],'Mobs','Rare','images/mob.svg',280,120,520,null,null,null,'Créature modifiée présente dans les Farmlands.','Créature de Farmlands · estimation'],
['Dancarok',['Dancarok'],'Mobs','Unique','images/golem.svg',22000,14000,34000,null,null,100,'Monture terrestre modifiée pouvant détruire des blocs avec une corne.','Monture · estimation'],
];
ITEMS.push(...EXTRA_ITEMS);
if(typeof CATEGORIES!=='undefined'&&!CATEGORIES.includes('Mobs'))CATEGORIES.push('Mobs');
console.info('[PriceCheck] Catalogue étendu chargé :',ITEMS.length,'items');
