const $=s=>document.querySelector(s);
const favKey='pricecheck:favorites',historyKey='pricecheck:history';
const getFav=()=>new Set(JSON.parse(localStorage.getItem(favKey)||'[]'));
const saveFav=s=>localStorage.setItem(favKey,JSON.stringify([...s]));
const getHistory=()=>JSON.parse(localStorage.getItem(historyKey)||'{}');
const itemName=new URLSearchParams(location.search).get('item')||'';
const app=$('#app');
const authConfig=window.PRICECHECK_AUTH||{};
const supabaseClient=window.supabase&&authConfig.supabaseUrl&&authConfig.supabaseAnonKey?window.supabase.createClient(authConfig.supabaseUrl,authConfig.supabaseAnonKey):null;
const LOCAL_IMAGES={'Pickaxe of the God':'images/pog.svg','Paladium':'images/paladium-ore.svg','Titane':'images/titane.svg','Améthyste':'images/amethyste.svg','Rubis':'images/rubis.svg','Saphir':'images/saphir.svg','Émeraude':'images/emeraude.svg','Obsidienne':'images/obsidienne.svg',"Perle de l'End":'images/perle-end.svg','Machine industrielle':'images/crusher.svg','Four amélioré':'images/four.svg','Pioche Paladium':'images/pioche-paladium.svg','Casque Paladium':'images/casque-paladium.svg','Plastron Paladium':'images/plastron-paladium.svg','Pomme dorée':'images/pomme-doree.svg','Pain':'images/pain.svg'};
const imageFor=n=>LOCAL_IMAGES[n]||'images/default.svg';
const money=v=>Number(v||0).toLocaleString('fr-FR')+' $';
const withTimeout=async(p,ms=5000)=>{let t;try{return await Promise.race([p,new Promise((_,r)=>t=setTimeout(()=>r(new Error('timeout')),ms))])}finally{clearTimeout(t)}};
let x=null;
function localFind(){try{if(typeof getItem==='function'){const v=getItem(itemName);if(v)return v}}catch(e){}try{if(typeof ITEMS!=='undefined'){return ITEMS.find(v=>String(v[0]).toLowerCase()===itemName.toLowerCase())}}catch(e){}return null}
function showError(message){if(app)app.innerHTML='<section class="panel"><span class="tag">⚠️ Erreur</span><h1 class="title">Impossible de charger cet item</h1><p class="muted">'+message+'</p><a class="btn primary" href="index.html">← Retour au catalogue</a></section>'}
function render(){if(!app)return;if(!x){showError('Cet item est introuvable dans le catalogue.');return}const fav=getFav(),isFav=fav.has(x[0]),h=getHistory()[x[0]]||[];let related=[];try{related=ITEMS.filter(a=>a!==x&&a[2]===x[2]).slice(0,6)}catch(e){}const crumb=$('#crumbItem');if(crumb)crumb.textContent=x[0];app.innerHTML='<section class="hero"><div class="hero-main"><div class="image-box"><img src="'+imageFor(x[0])+'" alt="'+x[0]+'" onerror="this.onerror=null;this.src=\'images/default.svg\'"></div><div><div class="eyebrow"><span class="tag">'+(x[2]||'Objet')+'</span></div><h1 class="title">'+x[0]+'</h1><p class="subtitle">'+(x[11]||'')+'</p><button id="favorite" class="favorite '+(isFav?'active':'')+'">'+(isFav?'★':'☆')+'</button></div></div><aside class="price-card"><div class="label">PRIX MOYEN</div><div class="value">'+money(x[5])+'</div><div class="delta">± '+money(Math.round(((x[7]||0)-(x[6]||0))/2))+'</div></aside></section><section class="spec-strip"><div class="spec"><span>NIVEAU</span><strong>'+(x[10]??'—')+'</strong></div><div class="spec"><span>DURABILITÉ</span><strong>'+(x[8]??'—')+'</strong></div><div class="spec"><span>DÉGÂTS</span><strong>'+(x[9]??'—')+'</strong></div><div class="spec"><span>CATÉGORIE</span><strong>'+(x[2]||'—')+'</strong></div></section><div class="two-col"><section class="panel"><h2>Craft / obtention</h2><p class="muted">'+(x[12]||'Informations à compléter.')+'</p></section><section class="panel"><h2>Items proches</h2><div class="related-grid">'+related.map(a=>'<a class="related-card" href="item.html?item='+encodeURIComponent(a[0])+'"><img src="'+imageFor(a[0])+'" alt="'+a[0]+'"><div class="name">'+a[0]+'</div><div class="rprice">'+money(a[5])+'</div></a>').join('')+'</div></section></div><section class="panel"><h2>Informations</h2><p class="muted">'+(x[11]||'Aucune description.')+'</p></section><section id="communityPrice" class="panel community"><h2>Prix communautaire</h2><p class="muted">Chargement des relevés…</p></section><section class="panel"><h2>Prix observés</h2><p class="muted">'+(h.length?'Historique disponible.':'Aucune observation locale.')+'</p></section><section class="panel"><h2>Alias</h2><div class="aliases">'+(x[1]||[]).map(a=>'<span>'+a+'</span>').join('')+'</div></section>';$('#favorite').onclick=()=>{const s=getFav();s.has(x[0])?s.delete(x[0]):s.add(x[0]);saveFav(s);render()};loadReports()}
async function loadReports(){const box=$('#communityPrice');if(!box||!x)return;if(!supabaseClient){box.innerHTML='<h2>Prix communautaire</h2><p class="muted">Les relevés communautaires sont indisponibles hors connexion.</p>';return}try{const r=await withTimeout(supabaseClient.from('price_report_public').select('price').eq('item_name',x[0]).limit(100));if(r.error)throw r.error;const rows=r.data||[];const vals=rows.map(a=>Number(a.price)).filter(Number.isFinite);const med=vals.length?vals.sort((a,b)=>a-b)[Math.floor(vals.length/2)]:0;box.innerHTML='<h2>Prix communautaire</h2><p>Prix conseillé : <b>'+money(med)+'</b></p><p class="muted">'+vals.length+' relevé(s)</p>'}catch(e){box.innerHTML='<h2>Prix communautaire</h2><p class="muted">Les relevés sont temporairement indisponibles.</p>'}}
async function syncRemote(){if(!supabaseClient||!itemName)return;try{const r=await withTimeout(supabaseClient.from('items').select('*').eq('name',itemName).maybeSingle());if(r.error||!r.data)return;const row=r.data;x=[row.name,row.aliases||[],row.category,row.rarity,imageFor(row.name),row.price,row.min_price,row.max_price,row.durability,row.damage,row.level,row.description,row.craft_text];render()}catch(e){}}
(function start(){try{x=localFind();render()}catch(e){showError('Une erreur JavaScript a empêché le chargement de la fiche.')}syncRemote()})();
setTimeout(()=>{if(app&&!x)showError('Le chargement a pris trop de temps. Recharge la page ou retourne au catalogue.')},6000);