(() => {
'use strict';
const $=s=>document.querySelector(s), itemName=new URLSearchParams(location.search).get('item')||'';
const app=$('#app'), favKey='pricecheck:favorites';
const favs=()=>new Set(JSON.parse(localStorage.getItem(favKey)||'[]'));
const saveFav=s=>localStorage.setItem(favKey,JSON.stringify([...s]));
const money=v=>`${Math.max(0,Math.round(Number(v)||0)).toLocaleString('fr-FR')} $`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const timeout=(p,ms=5000)=>Promise.race([p,new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout')),ms))]);
function findLocal(){try{if(typeof getItem==='function')return getItem(itemName)}catch{}try{if(Array.isArray(window.ITEMS))return ITEMS.find(i=>String(i[0]).toLowerCase()===itemName.toLowerCase()||i[1]?.some(a=>String(a).toLowerCase()===itemName.toLowerCase()))}catch{}return null}
function fallbackImage(){return 'images/default.svg'}
function showError(msg){app.innerHTML=`<section class="panel error"><div class="error-icon">⚠️</div><h1>Fiche indisponible</h1><p>${esc(msg)}</p><a class="btn primary" href="index.html">← Retour au catalogue</a></section>`}
function render(x){
 if(!x){showError('Cet item n’existe pas dans le catalogue local.');return}
 const fav=favs(),active=fav.has(x[0]);let related=[];try{related=(window.ITEMS||[]).filter(i=>i!==x&&i[2]===x[2]).slice(0,6)}catch{}
 app.innerHTML=`<section class="hero"><div class="hero-main"><div class="image-box"><img src="${esc(x[4]||fallbackImage())}" alt="${esc(x[0])}" onerror="this.onerror=null;this.src='images/default.svg'"></div><div class="hero-copy"><div class="eyebrow"><span class="tag">${esc(x[2]||'Objet')}</span><span class="rarity">${esc(x[3]||'Commun')}</span></div><h1>${esc(x[0])}</h1><p>${esc(x[11]||'Aucune description disponible.')}</p><button id="favorite" class="favorite ${active?'active':''}">${active?'★':'☆'} Favori</button></div></div><aside class="price-card"><span>PRIX INDICATIF</span><strong>${money(x[5])}</strong><small>Fourchette : ${money(x[6])} → ${money(x[7])}</small></aside></section><section class="spec-strip"><div><span>📈 Prix moyen</span><b>${money(x[5])}</b></div><div><span>📉 Minimum</span><b>${money(x[6])}</b></div><div><span>📊 Maximum</span><b>${money(x[7])}</b></div><div><span>🎮 Niveau</span><b>${x[10]??'—'}</b></div><div><span>🛠️ Durabilité</span><b>${esc(x[8]??'—')}</b></div></section><div class="grid2"><section class="panel"><h2>🧮 Comprendre les valeurs</h2><p>Le <b>niveau</b> indique le niveau de progression requis ou conseillé pour l’item. La <b>durabilité</b> correspond au nombre d’utilisations quand elle est connue. Les prix sont en <b>P$</b>.</p><div class="info-grid"><div><small>Niveau</small><strong>${x[10]??'Non renseigné'}</strong></div><div><small>Dégâts</small><strong>${esc(x[9]??'Non renseigné')}</strong></div><div><small>Catégorie</small><strong>${esc(x[2]||'Objet')}</strong></div></div></section><section class="panel"><h2>🔨 Craft / obtention</h2><p>${esc(x[12]||'Informations de craft à compléter.')}</p><button id="craftHelp" class="btn primary">Voir les détails</button></section></div><section class="panel community"><div class="section-head"><div><h2>👥 Prix proposés par la communauté</h2><p>Les prix validés sont affichés individuellement pour voir les propositions réelles.</p></div><span id="reportCount" class="count">Chargement…</span></div><div id="reports"><div class="loading-inline">Chargement des propositions…</div></div></section><section class="panel"><h2>🔎 Items proches</h2><div class="related-grid">${related.map(i=>`<a class="related" href="item.html?item=${encodeURIComponent(i[0])}"><img src="${esc(i[4]||fallbackImage())}" onerror="this.src='images/default.svg'" alt=""><b>${esc(i[0])}</b><span>${money(i[5])}</span></a>`).join('')||'<p class="muted">Aucun item proche.</p>'}</div></section>`;
 $('#favorite').onclick=()=>{const s=favs();active?s.delete(x[0]):s.add(x[0]);saveFav(s);render(x)};
 $('#craftHelp').onclick=()=>alert(`${x[0]}\n\n${x[12]||'Aucune recette détaillée disponible.'}`);
 loadReports(x[0]);
}
async function loadReports(name){const box=$('#reports'),count=$('#reportCount');if(!box)return;const cfg=window.PRICECHECK_AUTH;if(!cfg?.supabaseUrl||!cfg?.supabaseAnonKey){box.innerHTML='<p class="muted">Connexion communautaire indisponible.</p>';return}const headers={apikey:cfg.supabaseAnonKey,Authorization:`Bearer ${cfg.supabaseAnonKey}`};try{const url=`${cfg.supabaseUrl}/rest/v1/price_reports?select=price,created_at,status&item_name=eq.${encodeURIComponent(name)}&status=eq.accepted&order=created_at.desc&limit=30`;const rows=await timeout(fetch(url,{headers}).then(r=>{if(!r.ok)throw new Error(String(r.status));return r.json()}));const data=Array.isArray(rows)?rows:[];count.textContent=`${data.length} prix validé${data.length>1?'s':''}`;if(!data.length){box.innerHTML='<div class="empty">Aucune proposition validée pour le moment.</div>';return}const avg=data.reduce((s,r)=>s+Number(r.price||0),0)/data.length;box.innerHTML=`<div class="community-summary"><div><small>Moyenne des propositions</small><strong>${money(avg)}</strong></div><div><small>Plus bas</small><strong>${money(Math.min(...data.map(r=>Number(r.price)||0)))}</strong></div><div><small>Plus haut</small><strong>${money(Math.max(...data.map(r=>Number(r.price)||0)))}</strong></div></div><div class="report-list">${data.map((r,i)=>`<div class="report-row"><span>#${i+1}</span><b>${money(r.price)}</b><small>${new Date(r.created_at).toLocaleDateString('fr-FR')} · proposition validée</small></div>`).join('')}</div>`}catch(e){count.textContent='Indisponible';box.innerHTML='<div class="empty">Les propositions communautaires ne peuvent pas être récupérées pour le moment. La fiche de l’item reste disponible.</div>'}}
function boot(){const x=findLocal();if(x){render(x);return}setTimeout(()=>{const y=findLocal();y?render(y):showError('Le catalogue n’a pas pu être initialisé.')},1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
