(() => {
  'use strict';
  const CFG=window.PRICECHECK_AUTH;
  if(!CFG?.supabaseUrl||!CFG?.supabaseAnonKey)return;
  const ID_KEY='pricecheck:player-id',NAME_KEY='pricecheck:player-name',WALLET_KEY='pricecheck:wallet',PB_KEY='pricecheck:pb',JOB_KEY='pricecheck:job-levels',POG_KEY='pricecheck:pog-level';
  const readJson=key=>{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):null}catch{return null}};
  const clamp=(value,min,max)=>Math.max(min,Math.min(max,Math.round(Number(value)||min)));
  const firstValue=(obj,keys)=>{for(const key of keys){if(obj?.[key]!==undefined&&obj[key]!==null&&obj[key]!=='')return obj[key]}return null};
  const migrateLegacyProfile=()=>{const profileKeys=['pricecheck:profile','pricecheck:profile-data','pricecheck:profileData','pricecheck:player-profile','pricecheck:playerProfile','profileData','playerProfile'];const legacy=profileKeys.map(readJson).find(Boolean)||{};const name=firstValue(legacy,['display_name','displayName','username','pseudo','name','playerName']);if(!localStorage.getItem(NAME_KEY)&&name)localStorage.setItem(NAME_KEY,String(name).trim().slice(0,24));const wallet=firstValue(legacy,['wallet','balance','solde','money','moneyP$','p$']);if(!localStorage.getItem(WALLET_KEY)&&wallet!==null)localStorage.setItem(WALLET_KEY,String(Math.max(0,Math.round(Number(wallet)||0))));const pb=firstValue(legacy,['pb','PB','paladiumBlocks','paladium_block']);if(!localStorage.getItem(PB_KEY)&&pb!==null)localStorage.setItem(PB_KEY,String(Math.max(0,Math.round(Number(pb)||0))));const oldLevels=firstValue(legacy,['jobLevels','jobs','levels','metiers','job_levels'])||{};const current=readJson(JOB_KEY)||{};const aliases={Mineur:['Mineur','miner','miner_level','mineur_level'],Fermier:['Fermier','Farmer','fermier','farmer_level'],Chasseur:['Chasseur','Hunter','chasseur','hunter_level'],Alchimiste:['Alchimiste','Alchemist','alchimiste','alchemist_level']};for(const [job,keys] of Object.entries(aliases)){if(current[job]===undefined){const value=firstValue(oldLevels,keys);if(value!==null)current[job]=clamp(value,1,100)}}if(Object.keys(current).length)localStorage.setItem(JOB_KEY,JSON.stringify(current));const oldPog=firstValue(legacy,['pogLevel','pog_level','pog','POG']);if(!localStorage.getItem(POG_KEY)&&oldPog!==null)localStorage.setItem(POG_KEY,String(clamp(oldPog,1,100)));localStorage.setItem('pricecheck:profile-migrated','1')};
  migrateLegacyProfile();
  const getId=()=>{let id=localStorage.getItem(ID_KEY);if(!id){id=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem(ID_KEY,id)}return id};
  const getName=()=>String(localStorage.getItem(NAME_KEY)||'').trim().slice(0,24);
  const getWallet=()=>Math.max(0,Math.round(Number(localStorage.getItem(WALLET_KEY)||0)));
  const getPB=()=>Math.max(0,Math.round(Number(localStorage.getItem(PB_KEY)||0)));
  const getLevels=()=>readJson(JOB_KEY)||{};
  const headers=()=>({apikey:CFG.supabaseAnonKey,Authorization:`Bearer ${CFG.supabaseAnonKey}`,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates'});
  async function api(path,options={}){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),5000);try{const response=await fetch(`${CFG.supabaseUrl}/rest/v1/${path}`,{...options,headers:{...headers(),...(options.headers||{})},signal:controller.signal});if(!response.ok)throw new Error(`Supabase ${response.status}`);return response.status===204?null:response.json()}finally{clearTimeout(timeout)}}
  async function upsert(){const levels=getLevels();const body={player_id:getId(),display_name:getName()||'Joueur',wallet:getWallet(),pb:getPB(),miner_level:clamp(levels.Mineur,1,100),farmer_level:clamp(levels.Fermier,1,100),hunter_level:clamp(levels.Chasseur,1,100),alchemist_level:clamp(levels.Alchimiste,1,100),pog_level:clamp(localStorage.getItem(POG_KEY),1,100),last_seen:new Date().toISOString()};try{await api('player_stats',{method:'POST',body:JSON.stringify(body)});return true}catch(error){console.warn('Player stats sync unavailable',error);return false}}
  async function hydrateFromServer(){try{const rows=await api(`player_stats?select=display_name,wallet,pb,miner_level,farmer_level,hunter_level,alchemist_level,pog_level&player_id=eq.${encodeURIComponent(getId())}&limit=1`);const row=rows?.[0];if(!row)return false;localStorage.setItem(NAME_KEY,String(row.display_name||getName()).slice(0,24));localStorage.setItem(WALLET_KEY,String(Math.max(0,Math.round(Number(row.wallet)||0))));localStorage.setItem(PB_KEY,String(Math.max(0,Math.round(Number(row.pb)||0))));localStorage.setItem(JOB_KEY,JSON.stringify({Mineur:clamp(row.miner_level,1,100),Fermier:clamp(row.farmer_level,1,100),Chasseur:clamp(row.hunter_level,1,100),Alchimiste:clamp(row.alchemist_level,1,100)}));localStorage.setItem(POG_KEY,String(clamp(row.pog_level,1,100)));return true}catch(error){console.warn('Player profile hydration unavailable',error);return false}}
  const renderProfileEntry=()=>{const name=getName();if(!document.body||!name)return;const target=document.querySelector('[data-profile-entry="1"]');if(!target)return;target.title='Ouvrir mon profil';target.setAttribute('role','link');target.tabIndex=0;if(!target.dataset.profileClickBound){target.dataset.profileClickBound='1';target.addEventListener('click',()=>{location.href='profile.html'});target.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();location.href='profile.html'}})}};
  const setName=async value=>{const name=String(value||'').trim().slice(0,24);if(name)localStorage.setItem(NAME_KEY,name);else localStorage.removeItem(NAME_KEY);renderProfileEntry();await upsert();return name};
  const setWallet=async value=>{const wallet=Math.max(0,Math.round(Number(value)||0));localStorage.setItem(WALLET_KEY,String(wallet));renderProfileEntry();await upsert();return wallet};
  const setPB=async value=>{const pb=Math.max(0,Math.round(Number(value)||0));localStorage.setItem(PB_KEY,String(pb));renderProfileEntry();await upsert();return pb};
  window.PriceCheckPlayers={api,upsert,getId,getName,getWallet,getPB,getLevels,setName,setWallet,setPB,migrateLegacyProfile,hydrateFromServer};
  async function boot(){migrateLegacyProfile();const hydrated=await hydrateFromServer();if(!hydrated)await upsert();renderProfileEntry();window.addEventListener('storage',event=>{if([NAME_KEY,WALLET_KEY,PB_KEY,JOB_KEY,POG_KEY].includes(event.key))renderProfileEntry()});setInterval(()=>{void upsert();renderProfileEntry()},30000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else void boot();
})();
