(() => {
  'use strict';
  const CFG=window.PRICECHECK_AUTH;
  if(!CFG?.supabaseUrl||!CFG?.supabaseAnonKey)return;
  const ID_KEY='pricecheck:player-id',NAME_KEY='pricecheck:player-name',WALLET_KEY='pricecheck:wallet',PB_KEY='pricecheck:pb',JOB_KEY='pricecheck:job-levels',POG_KEY='pricecheck:pog-level';
  const readJson=key=>{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):null}catch{return null}};
  const firstValue=(obj,keys)=>{for(const k of keys){if(obj&&obj[k]!==undefined&&obj[k]!==null&&obj[k]!=='')return obj[k]}return null};
  const migrateLegacyProfile=()=>{const profileKeys=['pricecheck:profile','pricecheck:profile-data','pricecheck:profileData','pricecheck:player-profile','pricecheck:playerProfile','profileData','playerProfile'];const legacy=profileKeys.map(readJson).find(Boolean)||{};const name=firstValue(legacy,['display_name','displayName','username','pseudo','name','playerName']);if(!localStorage.getItem(NAME_KEY)&&name)localStorage.setItem(NAME_KEY,String(name).trim().slice(0,24));const wallet=firstValue(legacy,['wallet','balance','solde','money','moneyP$','p$']);if(!localStorage.getItem(WALLET_KEY)&&wallet!==null)localStorage.setItem(WALLET_KEY,String(Math.max(0,Math.round(Number(wallet)||0))));const pb=firstValue(legacy,['pb','PB','paladiumBlocks','paladium_block']);if(!localStorage.getItem(PB_KEY)&&pb!==null)localStorage.setItem(PB_KEY,String(Math.max(0,Math.round(Number(pb)||0))));const oldLevels=firstValue(legacy,['jobLevels','jobs','levels','metiers','job_levels'])||readJson('pricecheck:levels')||readJson('pricecheck:jobLevels')||readJson('pricecheck:metier-levels')||{};const current=readJson(JOB_KEY)||{};const aliases={Mineur:['Mineur','miner','miner_level','mineur_level'],Fermier:['Fermier','Farmer','fermier','farmer_level','fermeur'],Chasseur:['Chasseur','Hunter','chasseur','hunter_level'],Alchimiste:['Alchimiste','Alchemist','alchimiste','alchemist_level']};for(const [job,keys] of Object.entries(aliases))if(current[job]===undefined){const v=firstValue(oldLevels,keys);if(v!==null)current[job]=Math.max(1,Math.min(100,Math.round(Number(v)||1)))}if(Object.keys(current).length)localStorage.setItem(JOB_KEY,JSON.stringify(current));const oldPog=firstValue(legacy,['pogLevel','pog_level','pog','POG'])??localStorage.getItem('pricecheck:level-pog')??localStorage.getItem('pog-level');if(!localStorage.getItem(POG_KEY)&&oldPog!==null)localStorage.setItem(POG_KEY,String(Math.max(1,Math.min(100,Math.round(Number(oldPog)||1)))));localStorage.setItem('pricecheck:profile-migrated','1')};
  migrateLegacyProfile();
  const getId=()=>{let id=localStorage.getItem(ID_KEY);if(!id){id=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem(ID_KEY,id)}return id};
  const getName=()=>String(localStorage.getItem(NAME_KEY)||'').trim().slice(0,24),getWallet=()=>Math.max(0,Math.round(Number(localStorage.getItem(WALLET_KEY)||0))),getPB=()=>Math.max(0,Math.round(Number(localStorage.getItem(PB_KEY)||0)));const getLevels=()=>{try{return JSON.parse(localStorage.getItem(JOB_KEY)||'{}')}catch{return{}}};
  const headers=()=>({apikey:CFG.supabaseAnonKey,Authorization:`Bearer ${CFG.supabaseAnonKey}`,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates'});
  async function upsert(){const l=getLevels();const body={player_id:getId(),display_name:getName()||'Joueur',wallet:getWallet(),pb:getPB(),miner_level:Number(l.Mineur||1),farmer_level:Number(l.Fermier||1),hunter_level:Number(l.Chasseur||1),alchemist_level:Number(l.Alchimiste||1),pog_level:Number(localStorage.getItem(POG_KEY)||1),last_seen:new Date().toISOString()};try{const c=new AbortController(),t=setTimeout(()=>c.abort(),2500);const r=await fetch(`${CFG.supabaseUrl}/rest/v1/player_stats`,{method:'POST',headers:headers(),body:JSON.stringify(body),keepalive:true,signal:c.signal});clearTimeout(t);if(!r.ok)console.warn('Player stats sync HTTP',r.status)}catch(e){console.warn('Player stats sync unavailable',e)}}
  async function api(path,options={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),3000);try{const r=await fetch(`${CFG.supabaseUrl}/rest/v1/${path}`,{...options,headers:{...headers(),...(options.headers||{})},signal:c.signal});if(!r.ok)throw new Error(`Supabase ${r.status}`);return r.json()}finally{clearTimeout(t)}}
  async function hydrateFromServer(){try{const rows=await api(`player_stats?select=display_name,wallet,pb,miner_level,farmer_level,hunter_level,alchemist_level,pog_level&player_id=eq.${encodeURIComponent(getId())}&limit=1`);const r=rows?.[0];if(!r)return false;localStorage.setItem(NAME_KEY,String(r.display_name||getName()).slice(0,24));localStorage.setItem(WALLET_KEY,String(Math.max(0,Math.round(Number(r.wallet)||0))));localStorage.setItem(PB_KEY,String(Math.max(0,Math.round(Number(r.pb)||0))));localStorage.setItem(JOB_KEY,JSON.stringify({Mineur:Math.max(1,Math.min(100,Math.round(Number(r.miner_level)||1))),Fermier:Math.max(1,Math.min(100,Math.round(Number(r.farmer_level)||1))),Chasseur:Math.max(1,Math.min(100,Math.round(Number(r.hunter_level)||1))),Alchimiste:Math.max(1,Math.min(100,Math.round(Number(r.alchemist_level)||1)))}));localStorage.setItem(POG_KEY,String(Math.max(1,Math.min(100,Math.round(Number(r.pog_level)||1))));return true}catch(e){console.warn('Player profile hydration unavailable',e);return false}}
  const setName=async n=>{const value=String(n).trim().slice(0,24);if(value)localStorage.setItem(NAME_KEY,value);else localStorage.removeItem(NAME_KEY);void upsert();renderProfileEntry();return value},setWallet=n=>{localStorage.setItem(WALLET_KEY,String(Math.max(0,Math.round(Number(n)||0))));renderProfileEntry();void upsert();return getWallet()},setPB=n=>{localStorage.setItem(PB_KEY,String(Math.max(0,Math.round(Number(n)||0))));renderProfileEntry();void upsert();return getPB()};
  window.PriceCheckPlayers={upsert,api,getId,getName,getWallet,getPB,getLevels,setName,setWallet,setPB,migrateLegacyProfile,hydrateFromServer};
  const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  function injectProfileStyles(){if(document.getElementById('pricecheck-profile-entry-styles'))return;const style=document.createElement('style');style.id='pricecheck-profile-entry-styles';style.textContent='.pricecheck-profile-entry{width:100%;min-height:64px;display:flex!important;align-items:center;justify-content:space-between;gap:14px;padding:10px 18px!important;border-radius:18px;cursor:pointer!important;text-align:left;position:relative;overflow:hidden;transition:transform .18s ease,box-shadow .18s ease}.pricecheck-profile-entry::after{content:"";position:absolute;top:0;bottom:0;width:38%;left:-45%;background:linear-gradient(105deg,transparent,rgba(255,255,255,.42),transparent);transform:skewX(-18deg);animation:pcProfileSweep .82s linear infinite;pointer-events:none}.pricecheck-profile-entry:hover{transform:translateY(-1px);box-shadow:0 8px 22px rgba(0,0,0,.08)}@keyframes pcProfileSweep{0%{left:-45%}100%{left:115%}}.pc-profile-main{display:flex;align-items:center;gap:12px;min-width:0;position:relative;z-index:1}.pc-profile-avatar{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(135deg,#b86b35,#e5c98f);font-size:23px;flex:none}.pc-profile-copy{min-width:0}.pc-profile-name{font-weight:900;font-size:17px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pc-profile-label{font-size:10px;opacity:.6;text-transform:uppercase;letter-spacing:.12em;margin-top:2px}.pc-profile-stats{display:flex;justify-content:flex-end;gap:7px;flex-wrap:wrap;position:relative;z-index:1}.pc-profile-chip{padding:7px 10px;border-radius:999px;background:rgba(255,255,255,.42);font-size:11px;font-weight:800;white-space:nowrap}@media(max-width:700px){.pricecheck-profile-entry{align-items:flex-start}.pc-profile-stats{justify-content:flex-start}.pc-profile-chip{padding:6px 8px}.pc-profile-name{font-size:15px}}';document.head.appendChild(style)}
  function findProfileTarget(){const current=getName();const marked=document.querySelector('[data-profile-entry="1"]');if(marked)return marked;if(!current)return null;return [...document.querySelectorAll('body *')].find(el=>{if(el.children.length>2)return false;const t=String(el.textContent||'').trim();return t===current||t===`👤 ${current}`||t===`👤${current}`})||null}
  function renderProfileEntry(){const name=getName();if(!document.body||!name)return;injectProfileStyles();const target=findProfileTarget();if(!target)return;target.dataset.profileEntry='1';target.dataset.profileLink='1';target.setAttribute('role','link');target.setAttribute('tabindex','0');target.title='Ouvrir mon profil';target.classList.add('pricecheck-profile-entry');const l=getLevels();const jobs=[['M',l.Mineur],['F',l.Fermier],['A',l.Alchimiste],['C',l.Chasseur]].filter(([,v])=>Number(v)>0).map(([k,v])=>`${k} ${Number(v)}`).join(' · ')||'Métiers à renseigner';target.innerHTML=`<span class="pc-profile-main"><span class="pc-profile-avatar">👤</span><span class="pc-profile-copy"><span class="pc-profile-name">${esc(name)}</span><span class="pc-profile-label">Mon profil · ${jobs}</span></span></span><span class="pc-profile-stats"><span class="pc-profile-chip">💰 ${getWallet().toLocaleString('fr-FR')} P$</span><span class="pc-profile-chip">🪙 ${getPB().toLocaleString('fr-FR')} PB</span><span class="pc-profile-chip">⭐ POG ${Number(localStorage.getItem(POG_KEY)||1)}</span></span>`;if(!target.dataset.profileClickBound){target.dataset.profileClickBound='1';target.addEventListener('click',()=>location.href='profile.html');target.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();location.href='profile.html'}})}}
  async function boot(){migrateLegacyProfile();const hydrated=await hydrateFromServer();if(!hydrated)await upsert();renderProfileEntry();window.addEventListener('storage',e=>{if([NAME_KEY,WALLET_KEY,PB_KEY,JOB_KEY,POG_KEY].includes(e.key))renderProfileEntry()});setInterval(()=>{void upsert();renderProfileEntry()},30000);setTimeout(renderProfileEntry,500);setTimeout(renderProfileEntry,1500)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();