(() => {
'use strict';
const JOB_KEY='pricecheck:job-levels',POG_KEY='pricecheck:pog-level',NAME_KEY='pricecheck:player-name';
const levels=()=>{try{return JSON.parse(localStorage.getItem(JOB_KEY)||'{}')}catch{return{}}};
const saveLevels=()=>{const x=levels();[['lvlMiner','Mineur'],['lvlFarmer','Fermier'],['lvlHunter','Chasseur'],['lvlAlchemist','Alchimiste']].forEach(([id,k])=>{const e=document.getElementById(id);if(e)x[k]=Math.max(1,Math.min(100,Math.round(Number(e.value)||1)))});const p=document.getElementById('lvlPog');if(p)localStorage.setItem(POG_KEY,String(Math.max(1,Math.min(100,Math.round(Number(p.value)||1)))));localStorage.setItem(JOB_KEY,JSON.stringify(x));window.PriceCheckPlayers?.upsert?.();updateLabels()};
const updateLabels=()=>{const x=levels();[['lvlMiner','Mineur'],['lvlFarmer','Fermier'],['lvlHunter','Chasseur'],['lvlAlchemist','Alchimiste']].forEach(([id,k])=>{const e=document.getElementById(id),l=e?.previousElementSibling;if(e){e.value=x[k]||1;if(l)l.textContent=`${l.textContent.replace(/ — Niv\. \d+$/,'')} — Niv. ${e.value}`}});const p=document.getElementById('lvlPog');if(p)p.value=localStorage.getItem(POG_KEY)||1};
const isAdmin=async()=>{try{if(!window.supabase||!window.PRICECHECK_AUTH)return false;const c=window.supabase.createClient(window.PRICECHECK_AUTH.supabaseUrl,window.PRICECHECK_AUTH.supabaseAnonKey);const {data:{session}}=await c.auth.getSession();if(!session?.user?.id)return false;const {data}=await c.from('admins').select('user_id').eq('user_id',session.user.id).maybeSingle();return !!data}catch{return false}};
const run=async()=>{const name=document.getElementById('name');if(name){name.value=localStorage.getItem(NAME_KEY)||'';name.placeholder='Ton pseudo';const save=document.getElementById('saveName');if(save)save.onclick=async()=>{const value=name.value.trim().slice(0,24);if(!value){name.focus();return}localStorage.setItem(NAME_KEY,value);await window.PriceCheckPlayers?.setName?.(value);name.value=value;const h=document.querySelector('.profile-card h2');if(h)h.textContent=`👤 Profil de ${value}`};name.addEventListener('input',()=>name.setCustomValidity(''))}updateLabels();['lvlMiner','lvlFarmer','lvlHunter','lvlAlchemist','lvlPog'].forEach(id=>document.getElementById(id)?.addEventListener('input',saveLevels));const board=document.getElementById('board');if(board&&!window.PriceCheckPlayers){setTimeout(run,500);return}if(await isAdmin()){const card=document.querySelector('.profile-card');if(card&&!card.querySelector('.admin-badge')){const b=document.createElement('div');b.className='admin-badge';b.innerHTML='👑 <strong>Administrateur</strong><br><span>Ton compte dispose des droits administrateur.</span><a href="admin.html">Ouvrir le panneau admin →</a>';card.insertBefore(b,card.querySelector('.online'))}const nav=document.querySelector('.links');if(nav&&!nav.querySelector('a[href="admin.html"]'))nav.insertAdjacentHTML('beforeend','<a href="admin.html">⚙️ Admin</a>')}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();
