(() => {
'use strict';
if(window.__PC_PROFILE_FIX_V14__)return;window.__PC_PROFILE_FIX_V14__=true;
const JOB_KEY='pricecheck:job-levels',POG_KEY='pricecheck:pog-level',NAME_KEY='pricecheck:player-name';
const levels=()=>{try{return JSON.parse(localStorage.getItem(JOB_KEY)||'{}')}catch{return{}}};
const clamp=v=>Math.max(1,Math.min(100,Math.round(Number(v)||1)));
const esc=s=>String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const map={wallet:'wallet',miner:'miner_level',farmer:'farmer_level',hunter:'hunter_level',alchemist:'alchemist_level',pog:'pog_level'};
const label=k=>({wallet:'Portefeuille',miner:'Métier Mineur',farmer:'Métier Fermier',hunter:'Métier Chasseur',alchemist:'Métier Alchimiste',pog:'Niveau POG'}[k]||k);
const updateLabels=()=>{const x=levels();[['lvlMiner','Mineur'],['lvlFarmer','Fermier'],['lvlHunter','Chasseur'],['lvlAlchemist','Alchimiste']].forEach(([id,k])=>{const e=document.getElementById(id),l=e?.previousElementSibling;if(e){e.value=x[k]||1;if(l)l.textContent=`${l.textContent.replace(/ — Niv\. \d+$/,'')} — Niv. ${e.value}`}});const p=document.getElementById('lvlPog');if(p)p.value=localStorage.getItem(POG_KEY)||1};
const saveLevels=async()=>{const x=levels();[['lvlMiner','Mineur'],['lvlFarmer','Fermier'],['lvlHunter','Chasseur'],['lvlAlchemist','Alchimiste']].forEach(([id,k])=>{const e=document.getElementById(id);if(e)x[k]=clamp(e.value)});const p=document.getElementById('lvlPog');if(p)localStorage.setItem(POG_KEY,String(clamp(p.value)));localStorage.setItem(JOB_KEY,JSON.stringify(x));await window.PriceCheckPlayers?.upsert?.();updateLabels();await community()};
async function renderBoard(key,id){const p=window.PriceCheckPlayers,board=document.getElementById('board');if(!board)return;try{if(!p)throw new Error('player api unavailable');const rows=await p.api(`player_stats?select=player_id,display_name,wallet,pb,miner_level,farmer_level,hunter_level,alchemist_level,pog_level&display_name=neq.Joueur&order=${map[key]}.desc&limit=3`);const visible=rows.slice(0,3);while(visible.length<3)visible.push(null);board.innerHTML=visible.map((r,i)=>r?`<div class="row ${r.player_id===id?'me':''}"><span class="rank">#${i+1}</span><span class="name">${esc(r.display_name||'Joueur')} ${r.player_id===id?'(toi)':''}<small>${label(key)}</small></span><span class="value">${key==='wallet'?`${Number(r.wallet||0).toLocaleString('fr-FR')} P$`:`Niv. ${Number(r[map[key]]||1)}`}</span></div>`:`<div class="row"><span class="rank">#${i+1}</span><span class="name" style="opacity:.45">—</span><span class="value" style="opacity:.35">—</span></div>`).join('')}catch(e){const l=levels();const v=key==='wallet'?Number(localStorage.getItem('pricecheck:wallet')||0):({miner:l.Mineur||1,farmer:l.Fermier||1,hunter:l.Chasseur||1,alchemist:l.Alchimiste||1,pog:Number(localStorage.getItem(POG_KEY)||1)}[key]||1);board.innerHTML=`<div class="row me"><span class="rank">#1</span><span class="name">${esc(localStorage.getItem(NAME_KEY)||'Joueur')} (toi)<small>${label(key)} · mode local</small></span><span class="value">${key==='wallet'?`${v.toLocaleString('fr-FR')} P$`:`Niv. ${v}`}</span></div><div class="row"><span class="rank">#2</span><span class="name" style="opacity:.45">—</span><span class="value" style="opacity:.35">—</span></div><div class="row"><span class="rank">#3</span><span class="name" style="opacity:.45">—</span><span class="value" style="opacity:.35">—</span></div>`}}
async function community(){const p=window.PriceCheckPlayers;if(!p)return;const id=p.getId();try{await p.upsert();const online=await p.api(`player_stats?select=player_id&last_seen=gte.${encodeURIComponent(new Date(Date.now()-120000).toISOString())}`);const oe=document.getElementById('online');if(oe)oe.textContent=String(online.length);await renderBoard(document.querySelector('.tab.active')?.dataset.rank||'wallet',id)}catch(e){const oe=document.getElementById('online');if(oe&&oe.textContent==='—')oe.textContent='1';await renderBoard(document.querySelector('.tab.active')?.dataset.rank||'wallet',id)}}
const refreshTabs=()=>document.querySelectorAll('.tab').forEach(b=>b.onclick=async()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');await renderBoard(b.dataset.rank||'wallet',window.PriceCheckPlayers?.getId?.())});
const normalizeName=()=>{const input=document.getElementById('name');if(!input)return;const saved=(localStorage.getItem(NAME_KEY)||'').trim().slice(0,24);if(document.activeElement!==input&&input.value!==saved)input.value=saved;input.placeholder='Ton pseudo';const save=document.getElementById('saveName');if(save&&!save.dataset.v14){save.dataset.v14='1';save.onclick=async()=>{const value=input.value.trim().slice(0,24);if(!value){input.focus();return}localStorage.setItem(NAME_KEY,value);await window.PriceCheckPlayers?.setName?.(value);input.value=value;await community()}}};
const migrate=()=>{if(!localStorage.getItem(NAME_KEY)){for(const k of ['pricecheck:profile-name','pricecheck:username','pricecheck:pseudo','pricecheck:name']){const v=String(localStorage.getItem(k)||'').trim();if(v){localStorage.setItem(NAME_KEY,v.slice(0,24));break}}}if(!localStorage.getItem(JOB_KEY)){for(const k of ['pricecheck:levels','pricecheck:jobLevels','pricecheck:metier-levels']){const v=localStorage.getItem(k);if(v){localStorage.setItem(JOB_KEY,v);break}}}if(!localStorage.getItem(POG_KEY)){for(const k of ['pricecheck:pog','pricecheck:pogLevel','pricecheck:level-pog']){const v=localStorage.getItem(k);if(v){localStorage.setItem(POG_KEY,v);break}}}};
async function run(){migrate();normalizeName();updateLabels();refreshTabs();const btn=document.getElementById('saveLevels');if(btn)btn.onclick=saveLevels;await community()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
window.addEventListener('storage',e=>{if([NAME_KEY,JOB_KEY,POG_KEY].includes(e.key)){normalizeName();updateLabels();community()}});
setInterval(community,30000);
})();
