(() => {
'use strict';
if(window.__PC_PROFILE_FIX__)return;window.__PC_PROFILE_FIX__=true;
const JOB_KEY='pricecheck:job-levels',POG_KEY='pricecheck:pog-level',NAME_KEY='pricecheck:player-name';
const levels=()=>{try{return JSON.parse(localStorage.getItem(JOB_KEY)||'{}')}catch{return{}}};
const saveLevels=async()=>{const x=levels();[['lvlMiner','Mineur'],['lvlFarmer','Fermier'],['lvlHunter','Chasseur'],['lvlAlchemist','Alchimiste']].forEach(([id,k])=>{const e=document.getElementById(id);if(e)x[k]=Math.max(1,Math.min(100,Math.round(Number(e.value)||1)))});const p=document.getElementById('lvlPog');if(p)localStorage.setItem(POG_KEY,String(Math.max(1,Math.min(100,Math.round(Number(p.value)||1)))));localStorage.setItem(JOB_KEY,JSON.stringify(x));await window.PriceCheckPlayers?.upsert?.();updateLabels();refreshCommunity()};
const updateLabels=()=>{const x=levels();[['lvlMiner','Mineur'],['lvlFarmer','Fermier'],['lvlHunter','Chasseur'],['lvlAlchemist','Alchimiste']].forEach(([id,k])=>{const e=document.getElementById(id),l=e?.previousElementSibling;if(e){e.value=x[k]||1;if(l)l.textContent=`${l.textContent.replace(/ — Niv\. \d+$/,'')} — Niv. ${e.value}`}});const p=document.getElementById('lvlPog');if(p)p.value=localStorage.getItem(POG_KEY)||1};
const isAdmin=async()=>{try{if(!window.supabase||!window.PRICECHECK_AUTH)return false;const c=window.supabase.createClient(window.PRICECHECK_AUTH.supabaseUrl,window.PRICECHECK_AUTH.supabaseAnonKey);const {data:{session}}=await c.auth.getSession();if(!session?.user?.id)return false;const {data}=await c.from('admins').select('user_id').eq('user_id',session.user.id).maybeSingle();return !!data}catch{return false}};
const community=async()=>{const p=window.PriceCheckPlayers;if(!p)return;try{await p.upsert();const id=p.getId();const online=await p.api(`player_stats?select=player_id&last_seen=gte.${encodeURIComponent(new Date(Date.now()-90000).toISOString())}`);const oe=document.getElementById('online');if(oe)oe.textContent=String(online.length);const active=document.querySelector('.tab.active')?.dataset.rank||'wallet';await renderBoard(active,id)}catch(e){console.warn('PriceCheck community refresh',e)}};
const renderBoard=async(key,id)=>{const p=window.PriceCheckPlayers,board=document.getElementById('board');if(!p||!board)return;const map={wallet:'wallet',miner:'miner_level',farmer:'farmer_level',hunter:'hunter_level',alchemist:'alchemist_level',pog:'pog_level'};try{const rows=await p.api(`player_stats?select=player_id,display_name,wallet,pb,miner_level,farmer_level,hunter_level,alchemist_level,pog_level&order=${map[key]}.desc&limit=50`);board.innerHTML=rows.length?rows.map((r,i)=>`<div class="row ${r.player_id===id?'me':''}"><span class="rank">#${i+1}</span><span class="name">${String(r.display_name||'Joueur').replace(/[<>]/g,'')} ${r.player_id===id?'(toi)':''}<small>${key==='wallet'?'Portefeuille':key==='pog'?'Niveau POG':`Métier ${key.charAt(0).toUpperCase()+key.slice(1)}`}</small></span><span class="value">${key==='wallet'?`${Number(r.wallet||0).toLocaleString('fr-FR')} P$`:`Niv. ${Number(r[map[key]]||1)}`}</span></div>`).join(''):'<div class="muted">Aucun joueur enregistré pour le moment.</div>'}catch(e){board.innerHTML='<div class="notice">⚠️ Classement momentanément indisponible.</div>'}};
const refreshCommunity=()=>community();
const normalizeNameField=()=>{const input=document.getElementById('name');if(!input)return;const saved=localStorage.getItem(NAME_KEY)||'';input.value=saved;input.placeholder='Ton pseudo';const save=document.getElementById('saveName');if(save&&!save.dataset.pcBound){save.dataset.pcBound='1';save.onclick=async()=>{const value=input.value.trim().slice(0,24);if(!value){input.focus();return}localStorage.setItem(NAME_KEY,value);await window.PriceCheckPlayers?.setName?.(value);input.value=value;const h=document.querySelector('.profile-card h2');if(h)h.textContent=`👤 Profil de ${value}`;await community()}}};
const run=async()=>{normalizeNameField();updateLabels();const saveLevelsBtn=document.getElementById('saveLevels');if(saveLevelsBtn)saveLevelsBtn.onclick=saveLevels;const board=document.getElementById('board');if(board&&!window.PriceCheckPlayers){setTimeout(run,300);return}document.querySelectorAll('.links').forEach(l=>{const ps=[...l.querySelectorAll('a[href="profile.html"]')];ps.slice(1).forEach(a=>a.remove())});if(await isAdmin()){const card=document.querySelector('.profile-card');if(card&&!card.querySelector('.admin-badge')){const b=document.createElement('div');b.className='admin-badge';b.innerHTML='👑 <strong>Administrateur</strong><br><span>Ton compte dispose des droits administrateur.</span><a href="admin.html">Ouvrir le panneau admin →</a>';card.insertBefore(b,card.querySelector('.online'))}const nav=document.querySelector('.links');if(nav&&!nav.querySelector('a[href="admin.html"]'))nav.insertAdjacentHTML('beforeend','<a href="admin.html">⚙️ Admin</a>')}await community()};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
setInterval(normalizeNameField,1500);
setInterval(community,30000);
})();
